-- Production seed data
-- Generated: 2026-04-11T12:25:39.973048Z

SET FOREIGN_KEY_CHECKS=0;

-- temple_system_settings (31 rows)
TRUNCATE TABLE \`temple_system_settings\`;
INSERT INTO \`temple_system_settings\` (\`key\`, \`value\`, \`group\`, \`description\`, \`updated_by\`, \`updated_at\`) VALUES ('default_language', 'gu', 'general', 'Default language code', NULL, '2026-04-09 13:17:00');
INSERT INTO \`temple_system_settings\` (\`key\`, \`value\`, \`group\`, \`description\`, \`updated_by\`, \`updated_at\`) VALUES ('mail_driver', 'smtp', 'mail', NULL, NULL, '2026-04-09 13:17:00');
INSERT INTO \`temple_system_settings\` (\`key\`, \`value\`, \`group\`, \`description\`, \`updated_by\`, \`updated_at\`) VALUES ('mail_encryption', 'tls', 'mail', NULL, NULL, '2026-04-09 13:17:00');
INSERT INTO \`temple_system_settings\` (\`key\`, \`value\`, \`group\`, \`description\`, \`updated_by\`, \`updated_at\`) VALUES ('mail_from_address', 'website@patadiyahanumanji.com', 'mail', NULL, NULL, '2026-04-09 13:17:00');
INSERT INTO \`temple_system_settings\` (\`key\`, \`value\`, \`group\`, \`description\`, \`updated_by\`, \`updated_at\`) VALUES ('mail_from_name', 'Shree Pataliya Hanumanji Seva Trust - Gujarat', 'mail', NULL, NULL, '2026-04-09 13:17:00');
INSERT INTO \`temple_system_settings\` (\`key\`, \`value\`, \`group\`, \`description\`, \`updated_by\`, \`updated_at\`) VALUES ('mail_host', 'smtp.zoho.in', 'mail', NULL, NULL, '2026-04-09 13:17:00');
INSERT INTO \`temple_system_settings\` (\`key\`, \`value\`, \`group\`, \`description\`, \`updated_by\`, \`updated_at\`) VALUES ('mail_password', 'MKAgkGD9Rjx0', 'mail', NULL, NULL, '2026-04-09 13:17:00');
INSERT INTO \`temple_system_settings\` (\`key\`, \`value\`, \`group\`, \`description\`, \`updated_by\`, \`updated_at\`) VALUES ('mail_port', '587', 'mail', NULL, NULL, '2026-04-09 13:17:00');
INSERT INTO \`temple_system_settings\` (\`key\`, \`value\`, \`group\`, \`description\`, \`updated_by\`, \`updated_at\`) VALUES ('mail_test_recipient', 'sorathiyameet777@gmail.com', 'mail', NULL, NULL, '2026-04-09 13:17:00');
INSERT INTO \`temple_system_settings\` (\`key\`, \`value\`, \`group\`, \`description\`, \`updated_by\`, \`updated_at\`) VALUES ('mail_username', 'website@patadiyahanumanji.com', 'mail', NULL, NULL, '2026-04-09 13:17:00');
INSERT INTO \`temple_system_settings\` (\`key\`, \`value\`, \`group\`, \`description\`, \`updated_by\`, \`updated_at\`) VALUES ('razorpay_key_id', 'rzp_test_SbHxjallvtqkE2', 'payment', NULL, NULL, '2026-04-09 13:17:00');
INSERT INTO \`temple_system_settings\` (\`key\`, \`value\`, \`group\`, \`description\`, \`updated_by\`, \`updated_at\`) VALUES ('razorpay_key_secret', 'DX5SfKvRMoIKCm42I1tiRV9H', 'payment', NULL, NULL, '2026-04-09 13:17:00');
INSERT INTO \`temple_system_settings\` (\`key\`, \`value\`, \`group\`, \`description\`, \`updated_by\`, \`updated_at\`) VALUES ('razorpay_test_mode', '0', 'payment', NULL, NULL, '2026-04-09 13:17:00');
INSERT INTO \`temple_system_settings\` (\`key\`, \`value\`, \`group\`, \`description\`, \`updated_by\`, \`updated_at\`) VALUES ('razorpay_webhook_secret', '', 'payment', NULL, NULL, '2026-04-09 13:17:00');
INSERT INTO \`temple_system_settings\` (\`key\`, \`value\`, \`group\`, \`description\`, \`updated_by\`, \`updated_at\`) VALUES ('receipt_prefix', 'SPHST/80G', 'payment', '80G receipt number prefix', NULL, '2026-04-09 13:17:00');
INSERT INTO \`temple_system_settings\` (\`key\`, \`value\`, \`group\`, \`description\`, \`updated_by\`, \`updated_at\`) VALUES ('temple_rules', '<p>rule 1</p><p>rule 1</p><p>rule 1</p><p>rule 1</p><p>rule 1</p><p>rule 1</p><p>rule 1</p>', 'general', NULL, NULL, '2026-04-09 13:39:28');
INSERT INTO \`temple_system_settings\` (\`key\`, \`value\`, \`group\`, \`description\`, \`updated_by\`, \`updated_at\`) VALUES ('trust_80g_reg_no', '', 'trust', '80G registration number', NULL, '2026-04-09 13:17:00');
INSERT INTO \`temple_system_settings\` (\`key\`, \`value\`, \`group\`, \`description\`, \`updated_by\`, \`updated_at\`) VALUES ('trust_80g_validity', '', 'trust', '80G validity period', NULL, '2026-04-09 13:17:00');
INSERT INTO \`temple_system_settings\` (\`key\`, \`value\`, \`group\`, \`description\`, \`updated_by\`, \`updated_at\`) VALUES ('trust_address', 'Antarjal, Gandhidham, Kutch - 370205', 'trust', 'Trust registered address', NULL, '2026-04-09 13:17:00');
INSERT INTO \`temple_system_settings\` (\`key\`, \`value\`, \`group\`, \`description\`, \`updated_by\`, \`updated_at\`) VALUES ('trust_email', 'info@templeportal.in', 'trust', 'Trust contact email', NULL, '2026-04-09 13:17:00');
INSERT INTO \`temple_system_settings\` (\`key\`, \`value\`, \`group\`, \`description\`, \`updated_by\`, \`updated_at\`) VALUES ('trust_name', 'Shree Pataliya Hanumanji Seva Trust', 'trust', 'Official trust name', NULL, '2026-04-09 13:17:00');
INSERT INTO \`temple_system_settings\` (\`key\`, \`value\`, \`group\`, \`description\`, \`updated_by\`, \`updated_at\`) VALUES ('trust_pan', '', 'trust', 'Trust PAN number', NULL, '2026-04-09 13:17:00');
INSERT INTO \`temple_system_settings\` (\`key\`, \`value\`, \`group\`, \`description\`, \`updated_by\`, \`updated_at\`) VALUES ('trust_phone', '+91 XXXXXXXXXX', 'trust', 'Trust contact phone', NULL, '2026-04-09 13:17:00');
INSERT INTO \`temple_system_settings\` (\`key\`, \`value\`, \`group\`, \`description\`, \`updated_by\`, \`updated_at\`) VALUES ('whatsapp_access_token', '', 'whatsapp', NULL, NULL, '2026-04-09 13:17:00');
INSERT INTO \`temple_system_settings\` (\`key\`, \`value\`, \`group\`, \`description\`, \`updated_by\`, \`updated_at\`) VALUES ('whatsapp_api_url', '', 'whatsapp', NULL, NULL, '2026-04-09 13:17:00');
INSERT INTO \`temple_system_settings\` (\`key\`, \`value\`, \`group\`, \`description\`, \`updated_by\`, \`updated_at\`) VALUES ('whatsapp_business_id', '', 'whatsapp', NULL, NULL, '2026-04-09 13:17:00');
INSERT INTO \`temple_system_settings\` (\`key\`, \`value\`, \`group\`, \`description\`, \`updated_by\`, \`updated_at\`) VALUES ('whatsapp_phone_number_id', '', 'whatsapp', NULL, NULL, '2026-04-09 13:17:00');
INSERT INTO \`temple_system_settings\` (\`key\`, \`value\`, \`group\`, \`description\`, \`updated_by\`, \`updated_at\`) VALUES ('whatsapp_waba_id', '', 'whatsapp', NULL, NULL, '2026-04-09 13:17:00');
INSERT INTO \`temple_system_settings\` (\`key\`, \`value\`, \`group\`, \`description\`, \`updated_by\`, \`updated_at\`) VALUES ('whatsapp_webhook_verify_token', '', 'whatsapp', NULL, NULL, '2026-04-09 13:17:00');
INSERT INTO \`temple_system_settings\` (\`key\`, \`value\`, \`group\`, \`description\`, \`updated_by\`, \`updated_at\`) VALUES ('youtube_channel_id', 'MvStudioBidada', 'general', 'YouTube channel ID', NULL, '2026-04-09 13:17:00');
INSERT INTO \`temple_system_settings\` (\`key\`, \`value\`, \`group\`, \`description\`, \`updated_by\`, \`updated_at\`) VALUES ('youtube_live_url', 'https://www.youtube.com/watch?v=DjJBSKjbLNg', 'general', 'YouTube live stream URL', NULL, '2026-04-09 13:17:00');

-- temple_admin_users (1 rows)
TRUNCATE TABLE \`temple_admin_users\`;
INSERT INTO \`temple_admin_users\` (\`id\`, \`name\`, \`email\`, \`password\`, \`phone\`, \`avatar_path\`, \`is_active\`, \`remember_token\`, \`last_login_at\`, \`created_at\`, \`updated_at\`) VALUES ('1', 'Super Admin', 'sorathiyameet777@gmail.com', '$2y$12$H3f2A.ybSJW3E8SZT12mL.TJS9Cik3EvoGChMs.y1hpgSY5AMEUCe', '8980813268', NULL, '1', NULL, NULL, '2026-03-31 14:31:36', '2026-04-09 06:26:10');

-- roles (5 rows)
TRUNCATE TABLE \`roles\`;
INSERT INTO \`roles\` (\`id\`, \`name\`, \`guard_name\`, \`created_at\`, \`updated_at\`) VALUES ('1', 'super_admin', 'admin', '2026-03-31 14:31:36', '2026-03-31 14:31:36');
INSERT INTO \`roles\` (\`id\`, \`name\`, \`guard_name\`, \`created_at\`, \`updated_at\`) VALUES ('2', 'trustee', 'admin', '2026-03-31 14:31:36', '2026-03-31 14:31:36');
INSERT INTO \`roles\` (\`id\`, \`name\`, \`guard_name\`, \`created_at\`, \`updated_at\`) VALUES ('3', 'accountant', 'admin', '2026-03-31 14:31:36', '2026-03-31 14:31:36');
INSERT INTO \`roles\` (\`id\`, \`name\`, \`guard_name\`, \`created_at\`, \`updated_at\`) VALUES ('4', 'staff', 'admin', '2026-03-31 14:31:36', '2026-03-31 14:31:36');
INSERT INTO \`roles\` (\`id\`, \`name\`, \`guard_name\`, \`created_at\`, \`updated_at\`) VALUES ('5', 'volunteer', 'admin', '2026-03-31 14:31:36', '2026-03-31 14:31:36');

-- model_has_roles (1 rows)
TRUNCATE TABLE \`model_has_roles\`;
INSERT INTO \`model_has_roles\` (\`role_id\`, \`model_type\`, \`model_id\`) VALUES ('1', 'App\\Models\\AdminUser', '1');

-- temple_sevas (6 rows)
TRUNCATE TABLE \`temple_sevas\`;
INSERT INTO \`temple_sevas\` (\`id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`description_gu\`, \`description_hi\`, \`description_en\`, \`category\`, \`price\`, \`min_price\`, \`is_variable_price\`, \`image_path\`, \`slot_config\`, \`notification_config\`, \`linked_products\`, \`requires_booking\`, \`is_active\`, \`sort_order\`, \`assignee_id\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('1', 'શ્રૃંગાર સેવા', 'श्रृंगार सेवा', 'Shringar Seva', 'હનુમાનજી મહારાજની શ્રૃંગાર સેવા. ભગવાનને ફૂલ, માળા અને શ્રૃંગાર સામગ્રીથી સજાવવામાં આવે છે.', 'हनुमानजी महाराज की श्रृंगार सेवा. भगवान को फूल, माला और श्रृंगार सामग्री से सजाया जाता है.', 'Shringar Seva of Hanumanji Maharaj. The deity is adorned with flowers, garlands and decorative items.', 'shringar', '1100.00', NULL, '0', NULL, '{\"slot_duration_minutes\":\"30\",\"max_bookings_per_slot\":1,\"acceptance_period\":{\"type\":\"perpetual\"},\"weekly_schedule\":{\"default\":[\"06:00\",\"09:00\",\"12:00\",\"16:46\",\"17:00\"],\"monday\":null,\"tuesday\":null,\"wednesday\":null,\"thursday\":null,\"friday\":null,\"saturday\":null,\"sunday\":null},\"blackout_dates\":[{\"date\":\"2026-12-11\",\"reason\":\"Temple closed\"}],\"version\":2}', '{\"notify_on_booking\":false,\"booking_channels\":[],\"reminders\":[]}', '{\"type\":\"category\",\"category_id\":\"1\",\"label_gu\":\"Vastra Pasand Karo\",\"label_en\":\"Choose Offering\"}', '1', '1', '1', '1', '2026-03-31 14:31:36', '2026-04-09 10:49:45', NULL);
INSERT INTO \`temple_sevas\` (\`id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`description_gu\`, \`description_hi\`, \`description_en\`, \`category\`, \`price\`, \`min_price\`, \`is_variable_price\`, \`image_path\`, \`slot_config\`, \`notification_config\`, \`linked_products\`, \`requires_booking\`, \`is_active\`, \`sort_order\`, \`assignee_id\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('2', 'વસ્ત્ર સેવા', 'वस्त्र सेवा', 'Vastra Seva', 'હનુમાનજી મહારાજને નવા વસ્ત્રો અર્પણ કરવાની સેવા.', 'हनुमानजी महाराज को नए वस्त्र अर्पण करने की सेवा.', 'Offering new garments to Hanumanji Maharaj.', 'vastra', '501.00', NULL, '0', NULL, '{\"version\":2,\"slot_duration_minutes\":60,\"max_bookings_per_slot\":1,\"acceptance_period\":{\"type\":\"perpetual\",\"start_date\":null,\"end_date\":null},\"weekly_schedule\":{\"default\":[\"07:00\",\"11:00\",\"16:00\"],\"monday\":null,\"tuesday\":null,\"wednesday\":null,\"thursday\":null,\"friday\":null,\"saturday\":null,\"sunday\":null},\"blackout_dates\":[]}', NULL, NULL, '1', '1', '2', '1', '2026-03-31 14:31:36', '2026-04-09 07:01:23', NULL);
INSERT INTO \`temple_sevas\` (\`id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`description_gu\`, \`description_hi\`, \`description_en\`, \`category\`, \`price\`, \`min_price\`, \`is_variable_price\`, \`image_path\`, \`slot_config\`, \`notification_config\`, \`linked_products\`, \`requires_booking\`, \`is_active\`, \`sort_order\`, \`assignee_id\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('3', 'અન્નદાન સેવા', 'अन्नदान सेवा', 'Annadan Seva', 'ભોજનાલયમાં અન્નદાન સેવા. ભક્તોને પ્રસાદ ભોજન પીરસવામાં આવે છે.', 'भोजनालय में अन्नदान सेवा. भक्तों को प्रसाद भोजन परोसा जाता है.', 'Annadan Seva at the temple kitchen. Prasad meals are served to devotees.', 'annadan', '2100.00', NULL, '0', NULL, '{\"version\":2,\"slot_duration_minutes\":60,\"max_bookings_per_slot\":1,\"acceptance_period\":{\"type\":\"perpetual\",\"start_date\":null,\"end_date\":null},\"weekly_schedule\":{\"default\":[\"11:00\",\"18:00\"],\"monday\":null,\"tuesday\":null,\"wednesday\":null,\"thursday\":null,\"friday\":null,\"saturday\":null,\"sunday\":null},\"blackout_dates\":[]}', NULL, NULL, '1', '1', '3', '1', '2026-03-31 14:31:36', '2026-04-09 07:01:23', NULL);
INSERT INTO \`temple_sevas\` (\`id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`description_gu\`, \`description_hi\`, \`description_en\`, \`category\`, \`price\`, \`min_price\`, \`is_variable_price\`, \`image_path\`, \`slot_config\`, \`notification_config\`, \`linked_products\`, \`requires_booking\`, \`is_active\`, \`sort_order\`, \`assignee_id\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('4', 'મહાભિષેક પૂજા', 'महाभिषेक पूजा', 'Mahabhishek Puja', 'હનુમાનજી મહારાજનો મહાભિષેક. દૂધ, દહીં, ઘી, મધ અને ગંગાજળથી અભિષેક કરવામાં આવે છે.', 'हनुमानजी महाराज का महाभिषेक. दूध, दही, घी, शहद और गंगाजल से अभिषेक किया जाता है.', 'Mahabhishek of Hanumanji Maharaj. Abhishek performed with milk, curd, ghee, honey and Gangajal.', 'puja', '5100.00', NULL, '0', NULL, '{\"version\":2,\"slot_duration_minutes\":60,\"max_bookings_per_slot\":1,\"acceptance_period\":{\"type\":\"perpetual\",\"start_date\":null,\"end_date\":null},\"weekly_schedule\":{\"default\":[\"05:30\",\"10:00\",\"16:30\"],\"monday\":null,\"tuesday\":null,\"wednesday\":null,\"thursday\":null,\"friday\":null,\"saturday\":null,\"sunday\":null},\"blackout_dates\":[]}', NULL, NULL, '1', '1', '4', '1', '2026-03-31 14:31:36', '2026-04-09 07:01:23', NULL);
INSERT INTO \`temple_sevas\` (\`id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`description_gu\`, \`description_hi\`, \`description_en\`, \`category\`, \`price\`, \`min_price\`, \`is_variable_price\`, \`image_path\`, \`slot_config\`, \`notification_config\`, \`linked_products\`, \`requires_booking\`, \`is_active\`, \`sort_order\`, \`assignee_id\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('5', 'સુંદરકાંડ પાઠ', 'सुंदरकांड पाठ', 'Sundarkand Path', 'સુંદરકાંડનો સામૂહિક પાઠ. તુલસીદાસ રચિત રામચરિતમાનસના સુંદરકાંડનો પાઠ.', 'सुंदरकांड का सामूहिक पाठ. तुलसीदास रचित रामचरितमानस के सुंदरकांड का पाठ.', 'Collective recitation of Sundarkand from Tulsidas\' Ramcharitmanas.', 'special', '2501.00', NULL, '0', NULL, '{\"version\":2,\"slot_duration_minutes\":60,\"max_bookings_per_slot\":1,\"acceptance_period\":{\"type\":\"perpetual\",\"start_date\":null,\"end_date\":null},\"weekly_schedule\":{\"default\":[\"17:00\"],\"monday\":null,\"tuesday\":null,\"wednesday\":null,\"thursday\":null,\"friday\":null,\"saturday\":null,\"sunday\":null},\"blackout_dates\":[]}', NULL, NULL, '1', '1', '5', '1', '2026-03-31 14:31:36', '2026-04-09 07:01:23', NULL);
INSERT INTO \`temple_sevas\` (\`id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`description_gu\`, \`description_hi\`, \`description_en\`, \`category\`, \`price\`, \`min_price\`, \`is_variable_price\`, \`image_path\`, \`slot_config\`, \`notification_config\`, \`linked_products\`, \`requires_booking\`, \`is_active\`, \`sort_order\`, \`assignee_id\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('6', 'સામાન્ય દાન', 'सामान्य दान', 'General Donation', 'મંદિરના વિકાસ અને સેવા કાર્યો માટે સામાન્ય દાન.', 'मंदिर के विकास और सेवा कार्यों के लिए सामान्य दान.', 'General donation for temple development and service activities.', 'other', '100.00', '100.00', '1', NULL, NULL, NULL, NULL, '0', '1', '6', '1', '2026-03-31 14:31:36', '2026-03-31 14:31:36', NULL);

-- temple_donation_types (4 rows)
TRUNCATE TABLE \`temple_donation_types\`;
INSERT INTO \`temple_donation_types\` (\`id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`slug\`, \`description\`, \`extra_fields\`, \`greeting_card_config\`, \`greeting_card_template\`, \`is_active\`, \`sort_order\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('1', 'સામાન્ય દાન', 'सामान्य दान', 'General Donation', 'general', NULL, '[{\"key\":\"Birthday_Name\",\"label_gu\":\"KONO JANAMDIVAS CHE ? \",\"label_en\":\"WHOSE BDAY IT IS ?\",\"type\":\"text\",\"required\":true},{\"key\":\"Birthday_Age\",\"label_gu\":\"BDAY AGE \",\"label_en\":\"UMAR ?\",\"type\":\"number\",\"required\":true},{\"key\":\"photo\",\"label_gu\":\"photoooo\",\"label_en\":\"photo\",\"type\":\"image\",\"required\":true}]', '{\"overlays\":[{\"field_key\":\"_donor_name\",\"type\":\"text\",\"x\":50,\"y\":50,\"font_size\":32,\"color\":\"#881337\"},{\"field_key\":\"_amount\",\"type\":\"text\",\"x\":831,\"y\":87,\"font_size\":32,\"color\":\"#881337\"},{\"field_key\":\"_date\",\"type\":\"text\",\"x\":49,\"y\":106,\"font_size\":32,\"color\":\"#881337\"},{\"field_key\":\"_temple_name\",\"type\":\"text\",\"x\":567,\"y\":34,\"font_size\":32,\"color\":\"#881337\"},{\"field_key\":\"Birthday_Name\",\"type\":\"text\",\"x\":222,\"y\":221,\"font_size\":32,\"color\":\"#881337\"},{\"field_key\":\"Birthday_Age\",\"type\":\"text\",\"x\":763,\"y\":215,\"font_size\":32,\"color\":\"#881337\"},{\"field_key\":\"photo\",\"type\":\"image\",\"x\":221,\"y\":461,\"width\":563,\"height\":563}],\"send_via_email\":true,\"send_via_whatsapp\":true,\"show_on_thankyou\":true}', 'greeting-templates/01KNS3W5C2DT2CZ4RHRCMF2S3V.webp', '1', '0', '2026-04-09 11:46:56', '2026-04-09 13:05:33', NULL);
INSERT INTO \`temple_donation_types\` (\`id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`slug\`, \`description\`, \`extra_fields\`, \`greeting_card_config\`, \`greeting_card_template\`, \`is_active\`, \`sort_order\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('2', 'અન્નદાન', 'अन्नदान', 'Annadan', 'annadan', NULL, NULL, NULL, NULL, '1', '1', '2026-04-09 11:46:56', '2026-04-09 11:46:56', NULL);
INSERT INTO \`temple_donation_types\` (\`id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`slug\`, \`description\`, \`extra_fields\`, \`greeting_card_config\`, \`greeting_card_template\`, \`is_active\`, \`sort_order\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('3', 'નિર્માણ / જીર્ણોદ્ધાર', 'निर्माण / जीर्णोद्धार', 'Construction', 'construction', NULL, NULL, NULL, NULL, '1', '2', '2026-04-09 11:46:56', '2026-04-09 11:46:56', NULL);
INSERT INTO \`temple_donation_types\` (\`id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`slug\`, \`description\`, \`extra_fields\`, \`greeting_card_config\`, \`greeting_card_template\`, \`is_active\`, \`sort_order\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('4', 'ઉત્સવ / તહેવાર', 'उत्सव / त्योहार', 'Festival', 'festival', NULL, NULL, NULL, NULL, '1', '3', '2026-04-09 11:46:56', '2026-04-09 11:46:56', NULL);

-- temple_events (4 rows)
TRUNCATE TABLE \`temple_events\`;
INSERT INTO \`temple_events\` (\`id\`, \`title_gu\`, \`title_hi\`, \`title_en\`, \`description_gu\`, \`description_hi\`, \`description_en\`, \`start_date\`, \`end_date\`, \`start_time\`, \`end_time\`, \`location\`, \`image_path\`, \`is_featured\`, \`status\`, \`event_type\`, \`created_by\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('1', 'હનુમાન જયંતિ મહોત્સવ', 'हनुमान जयंती महोत्सव', 'Hanuman Jayanti Celebration', 'શ્રી પાતળિયા હનુમાનજી ધામ ખાતે હનુમાન જયંતિનો ભવ્ય ઉત્સવ. સવારે વિશેષ અભિષેક, મહાપૂજા, સુંદરકાંડ પાઠ, ભંડારા અને સાંજે ભવ્ય આરતી.', 'श्री पातळिया हनुमानजी धाम पर हनुमान जयंती का भव्य उत्सव।', NULL, '2026-04-15', '2026-04-15', '05:00:00', '21:00:00', 'Shree Pataliya Hanumanji Temple, Antarjal', NULL, '1', 'published', 'festival', NULL, '2026-03-31 14:31:36', '2026-03-31 14:31:36', NULL);
INSERT INTO \`temple_events\` (\`id\`, \`title_gu\`, \`title_hi\`, \`title_en\`, \`description_gu\`, \`description_hi\`, \`description_en\`, \`start_date\`, \`end_date\`, \`start_time\`, \`end_time\`, \`location\`, \`image_path\`, \`is_featured\`, \`status\`, \`event_type\`, \`created_by\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('2', 'શ્રી રામ નવમી ઉત્સવ', 'श्री राम नवमी उत्सव', 'Shri Ram Navami Festival', 'ભગવાન શ્રી રામના જન્મોત્સવની ધામધૂમથી ઉજવણી. સવારે રામચરિતમાનસ પાઠ, બપોરે ભંડારા અને સાંજે ભવ્ય ઝાંકી.', NULL, NULL, '2026-04-25', '2026-04-25', '06:00:00', '22:00:00', 'Shree Pataliya Hanumanji Temple, Antarjal', NULL, '1', 'published', 'festival', NULL, '2026-03-31 14:31:36', '2026-03-31 14:31:36', NULL);
INSERT INTO \`temple_events\` (\`id\`, \`title_gu\`, \`title_hi\`, \`title_en\`, \`description_gu\`, \`description_hi\`, \`description_en\`, \`start_date\`, \`end_date\`, \`start_time\`, \`end_time\`, \`location\`, \`image_path\`, \`is_featured\`, \`status\`, \`event_type\`, \`created_by\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('3', 'સાપ્તાહિક સુંદરકાંડ પાઠ', 'साप्ताहिक सुंदरकांड पाठ', 'Weekly Sundarkand Path', 'દર શનિવારે સાંજે ૫:૦૦ વાગ્યે સુંદરકાંડનો સામૂહિક પાઠ. તમામ ભક્તોને ભાગ લેવા વિનંતી.', NULL, NULL, '2026-04-04', NULL, '17:00:00', '19:30:00', 'Shree Pataliya Hanumanji Temple, Antarjal', NULL, '0', 'published', 'satsang', NULL, '2026-03-31 14:31:36', '2026-03-31 14:31:36', NULL);
INSERT INTO \`temple_events\` (\`id\`, \`title_gu\`, \`title_hi\`, \`title_en\`, \`description_gu\`, \`description_hi\`, \`description_en\`, \`start_date\`, \`end_date\`, \`start_time\`, \`end_time\`, \`location\`, \`image_path\`, \`is_featured\`, \`status\`, \`event_type\`, \`created_by\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('4', 'દિવાળી મહોત્સવ', 'दिवाली महोत्सव', 'Diwali Festival', 'દિવાળી ના પાવન પ્રસંગે મંદિરમાં ભવ્ય દીપોત્સવ અને લક્ષ્મી પૂજા.', NULL, NULL, '2026-10-31', '2026-11-04', NULL, NULL, 'Shree Pataliya Hanumanji Temple, Antarjal', NULL, '1', 'published', 'festival', NULL, '2026-03-31 14:31:36', '2026-03-31 14:31:36', NULL);

-- temple_announcements (3 rows)
TRUNCATE TABLE \`temple_announcements\`;
INSERT INTO \`temple_announcements\` (\`id\`, \`title_gu\`, \`title_hi\`, \`title_en\`, \`body_gu\`, \`body_hi\`, \`body_en\`, \`image_path\`, \`is_urgent\`, \`published_at\`, \`expires_at\`, \`is_active\`, \`created_by\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('1', 'હનુમાન જયંતિ મહોત્સવ — ૧૫ એપ્રિલ ૨૦૨૬', 'हनुमान जयंती महोत्सव — 15 अप्रैल 2026', 'Hanuman Jayanti Celebration — 15 April 2026', 'શ્રી પાતળિયા હનુમાનજી મંદિરમાં હનુમાન જયંતિનો ભવ્ય ઉત્સવ ઉજવવામાં આવશે. સવારે ૫:૦૦ વાગ્યાથી વિશેષ પૂજા અર્ચના શરૂ થશે. તમામ ભક્તોને ઉપસ્થિત રહેવા વિનંતી.', 'श्री पातळिया हनुमानजी मंदिर में हनुमान जयंती का भव्य उत्सव मनाया जाएगा।', NULL, NULL, '1', '2026-03-31 14:31:36', '2026-04-20 14:31:36', '1', NULL, '2026-03-31 14:31:36', '2026-03-31 14:31:36', NULL);
INSERT INTO \`temple_announcements\` (\`id\`, \`title_gu\`, \`title_hi\`, \`title_en\`, \`body_gu\`, \`body_hi\`, \`body_en\`, \`image_path\`, \`is_urgent\`, \`published_at\`, \`expires_at\`, \`is_active\`, \`created_by\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('2', 'દૈનિક અન્નદાન સેવા ચાલુ છે', 'दैनिक अन्नदान सेवा जारी है', 'Daily Annadan Seva is active', 'મંદિર ભોજનાલયમાં દૈનિક અન્નદાન સેવા ચાલુ છે. બપોરે ૧૧:૩૦ થી ૧:૩૦ સુધી ભોજન પ્રસાદ વિતરણ થાય છે.', 'मंदिर भोजनालय में दैनिक अन्नदान सेवा जारी है।', NULL, NULL, '0', '2026-03-26 14:31:36', NULL, '1', NULL, '2026-03-31 14:31:36', '2026-03-31 14:31:36', NULL);
INSERT INTO \`temple_announcements\` (\`id\`, \`title_gu\`, \`title_hi\`, \`title_en\`, \`body_gu\`, \`body_hi\`, \`body_en\`, \`image_path\`, \`is_urgent\`, \`published_at\`, \`expires_at\`, \`is_active\`, \`created_by\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('3', 'મંદિર જીર્ણોદ્ધાર કાર્ય પ્રગતિમાં', 'मंदिर जीर्णोद्धार कार्य प्रगति में', 'Temple renovation work in progress', 'મંદિરના જીર્ણોદ્ધાર કાર્યમાં ભક્તોનો સહકાર અમૂલ્ય છે. દાન કરી મંદિરના વિકાસમાં યોગદાન આપો.', 'मंदिर के जीर्णोद्धार कार्य में भक्तों का सहयोग अमूल्य है।', NULL, NULL, '0', '2026-03-21 14:31:36', NULL, '1', NULL, '2026-03-31 14:31:36', '2026-03-31 14:31:36', NULL);

-- temple_halls (2 rows)
TRUNCATE TABLE \`temple_halls\`;
INSERT INTO \`temple_halls\` (\`id\`, \`name\`, \`description\`, \`capacity\`, \`price_per_day\`, \`price_per_half_day\`, \`amenities\`, \`rules\`, \`image_path\`, \`is_active\`, \`created_at\`, \`updated_at\`) VALUES ('1', 'સભા મંડપ2wqe', 'મંદિર પરિસરમાં આવેલો વિશાળ સભા મંડપ. સત્સંગ, ભજન, લગ્ન પ્રસંગ માટે ઉપલબ્ધ.', '500', '15000.00', '8000.00', '[\"AC\",\"Sound System\",\"Projector\",\"Stage\",\"Parking\"]', NULL, NULL, '1', '2026-03-31 14:31:36', '2026-04-09 14:47:35');
INSERT INTO \`temple_halls\` (\`id\`, \`name\`, \`description\`, \`capacity\`, \`price_per_day\`, \`price_per_half_day\`, \`amenities\`, \`rules\`, \`image_path\`, \`is_active\`, \`created_at\`, \`updated_at\`) VALUES ('2', 'યાત્રીવાસ હોલ', 'નાના સમારંભ અને મિટિંગ માટે યોગ્ય.', '100', '5000.00', '3000.00', '[\"Fan\",\"Sound System\",\"Chairs\"]', NULL, NULL, '1', '2026-03-31 14:31:36', '2026-04-09 11:15:16');

-- temple_darshan_timings (2 rows)
TRUNCATE TABLE \`temple_darshan_timings\`;
INSERT INTO \`temple_darshan_timings\` (\`id\`, \`day_type\`, \`label\`, \`morning_open\`, \`morning_close\`, \`afternoon_open\`, \`afternoon_close\`, \`evening_open\`, \`evening_close\`, \`aarti_morning\`, \`aarti_evening\`, \`special_note_gu\`, \`special_note_hi\`, \`special_note_en\`, \`effective_from\`, \`effective_until\`, \`is_active\`, \`created_at\`, \`updated_at\`) VALUES ('1', 'regular', 'Regular Day', '05:30:00', '11:30:00', NULL, NULL, '16:00:00', '20:30:00', '06:00:00', '19:00:00', NULL, NULL, NULL, NULL, NULL, '1', '2026-03-31 14:31:36', '2026-04-09 13:39:28');
INSERT INTO \`temple_darshan_timings\` (\`id\`, \`day_type\`, \`label\`, \`morning_open\`, \`morning_close\`, \`afternoon_open\`, \`afternoon_close\`, \`evening_open\`, \`evening_close\`, \`aarti_morning\`, \`aarti_evening\`, \`special_note_gu\`, \`special_note_hi\`, \`special_note_en\`, \`effective_from\`, \`effective_until\`, \`is_active\`, \`created_at\`, \`updated_at\`) VALUES ('2', 'sunday', 'Sunday', '05:00:00', '12:00:00', NULL, NULL, '16:00:00', '21:00:00', '05:30:00', '19:30:00', NULL, NULL, NULL, NULL, NULL, '1', '2026-03-31 14:31:36', '2026-04-09 13:39:28');

-- temple_product_categories (4 rows)
TRUNCATE TABLE \`temple_product_categories\`;
INSERT INTO \`temple_product_categories\` (\`id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`slug\`, \`description\`, \`image_path\`, \`sort_order\`, \`is_active\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('1', 'વસ્ત્ર', 'वस्त्र', 'Religious Garments', 'religious-garments', 'શ્રી પાતળિયા હનુમાનજી મંદિરમાં ભગવાનને અર્પણ કરવા માટેના પવિત્ર વસ્ત્રો અને શ્રૃંગાર સામગ્રી.', NULL, '1', '1', '2026-04-09 09:40:21', '2026-04-09 09:40:21', NULL);
INSERT INTO \`temple_product_categories\` (\`id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`slug\`, \`description\`, \`image_path\`, \`sort_order\`, \`is_active\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('2', 'પ્રસાદ', 'प्रसाद', 'Sacred Sweets', 'sacred-sweets', 'મંદિરના પવિત્ર પ્રસાદ — હનુમાનજીને ધરાવેલ મીઠાઈઓ અને લાડુ.', NULL, '2', '1', '2026-04-09 09:40:21', '2026-04-09 09:40:21', NULL);
INSERT INTO \`temple_product_categories\` (\`id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`slug\`, \`description\`, \`image_path\`, \`sort_order\`, \`is_active\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('3', 'પુસ્તકો', 'पुस्तकें', 'Religious Publications', 'religious-publications', 'ધાર્મિક પુસ્તકો, હનુમાન ચાલીસા, સુંદરકાંડ અને અન્ય આધ્યાત્મિક સાહિત્ય.', NULL, '3', '1', '2026-04-09 09:40:21', '2026-04-09 09:40:21', NULL);
INSERT INTO \`temple_product_categories\` (\`id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`slug\`, \`description\`, \`image_path\`, \`sort_order\`, \`is_active\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('4', 'પૂજા સામગ્રી', 'पूजा सामग्री', 'Devotional Accessories', 'devotional-accessories', 'માળા, ફોટો ફ્રેમ, કીચેન અને અન્ય ભક્તિ સામગ્રી — મંદિરની યાદગીરી માટે.', NULL, '4', '1', '2026-04-09 09:40:21', '2026-04-09 09:40:21', NULL);

-- temple_products (33 rows)
TRUNCATE TABLE \`temple_products\`;
INSERT INTO \`temple_products\` (\`id\`, \`category_id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`slug\`, \`description_gu\`, \`description_hi\`, \`description_en\`, \`price\`, \`stock_quantity\`, \`image_path\`, \`is_active\`, \`is_featured\`, \`is_seva_only\`, \`has_variants\`, \`variants\`, \`sort_order\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('1', '1', 'શ્રી હનુમાનજી વસ્ત્ર - લાલ', 'श्री हनुमानजी वस्त्र - लाल', 'Red Hanuman Vastra', 'red-hanuman-vastra', 'શ્રી પાતળિયા હનુમાનજી મંદિરમાં ભગવાનને અર્પણ કરવા માટેનો લાલ રંગનો પવિત્ર વસ્ત્ર. શુદ્ધ કોટન કાપડમાંથી બનાવેલ, ઝરી બોર્ડર સાથે.', 'श्री पातलिया हनुमानजी मंदिर में भगवान को अर्पण करने के लिए लाल रंग का पवित्र वस्त्र. शुद्ध कॉटन कपड़े से बना, ज़री बॉर्डर के साथ.', 'Sacred red garment for offering to Hanumanji at Shree Pataliya Hanumanji Temple. Made from pure cotton fabric with zari border.', '1100.00', '25', NULL, '1', '1', '0', '0', NULL, '1', '2026-04-09 09:40:21', '2026-04-09 09:40:21', NULL);
INSERT INTO \`temple_products\` (\`id\`, \`category_id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`slug\`, \`description_gu\`, \`description_hi\`, \`description_en\`, \`price\`, \`stock_quantity\`, \`image_path\`, \`is_active\`, \`is_featured\`, \`is_seva_only\`, \`has_variants\`, \`variants\`, \`sort_order\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('2', '1', 'શ્રી હનુમાનજી વસ્ત્ર - કેસરી', 'श्री हनुमानजी वस्त्र - केसरी', 'Saffron Hanuman Vastra', 'saffron-hanuman-vastra', 'કેસરી રંગનો પવિત્ર વસ્ત્ર — હનુમાનજીનો પ્રિય રંગ. શુદ્ધ કોટન કાપડ, સુંદર ભરતકામ સાથે.', 'केसरी रंग का पवित्र वस्त्र — हनुमानजी का प्रिय रंग. शुद्ध कॉटन कपड़ा, सुंदर कढ़ाई के साथ.', 'Sacred saffron garment — Hanumanji\'s favourite colour. Pure cotton fabric with beautiful embroidery.', '1100.00', '13', NULL, '1', '1', '1', '0', NULL, '2', '2026-04-09 09:40:21', '2026-04-09 13:24:46', NULL);
INSERT INTO \`temple_products\` (\`id\`, \`category_id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`slug\`, \`description_gu\`, \`description_hi\`, \`description_en\`, \`price\`, \`stock_quantity\`, \`image_path\`, \`is_active\`, \`is_featured\`, \`is_seva_only\`, \`has_variants\`, \`variants\`, \`sort_order\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('3', '1', 'શ્રી હનુમાનજી શ્રૃંગાર વસ્ત્ર', 'श्री हनुमानजी श्रृंगार वस्त्र', 'Shringar Vastra Set', 'shringar-vastra-set', 'સંપૂર્ણ શ્રૃંગાર વસ્ત્ર સેટ — ઉત્તરીય, ધોતી અને પટકો સહિત. વિશેષ પ્રસંગોએ હનુમાનજીના શ્રૃંગાર માટે ઉપયોગી.', 'संपूर्ण श्रृंगार वस्त्र सेट — उत्तरीय, धोती और पटका सहित. विशेष अवसरों पर हनुमानजी के श्रृंगार के लिए उपयोगी.', 'Complete Shringar Vastra set including uttariya, dhoti and patka. Ideal for special occasion adornment of Hanumanji.', '2100.00', '13', NULL, '1', '0', '0', '0', NULL, '3', '2026-04-09 09:40:21', '2026-04-09 09:40:21', NULL);
INSERT INTO \`temple_products\` (\`id\`, \`category_id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`slug\`, \`description_gu\`, \`description_hi\`, \`description_en\`, \`price\`, \`stock_quantity\`, \`image_path\`, \`is_active\`, \`is_featured\`, \`is_seva_only\`, \`has_variants\`, \`variants\`, \`sort_order\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('4', '1', 'મુકુટ અને વસ્ત્ર સેટ', 'मुकुट और वस्त्र सेट', 'Mukut and Vastra Set', 'mukut-and-vastra-set', 'સુંદર મુકુટ સાથે મેચિંગ વસ્ત્ર સેટ. ઝરી અને ભરતકામથી સુશોભિત, મંદિરના મહોત્સવો માટે ઉત્તમ.', 'सुंदर मुकुट के साथ मैचिंग वस्त्र सेट. ज़री और कढ़ाई से सुशोभित, मंदिर के महोत्सवों के लिए उत्तम.', 'Beautiful crown with matching vastra set. Adorned with zari and embroidery, perfect for temple festivals.', '3500.00', '20', NULL, '1', '0', '0', '0', NULL, '4', '2026-04-09 09:40:21', '2026-04-09 09:40:21', NULL);
INSERT INTO \`temple_products\` (\`id\`, \`category_id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`slug\`, \`description_gu\`, \`description_hi\`, \`description_en\`, \`price\`, \`stock_quantity\`, \`image_path\`, \`is_active\`, \`is_featured\`, \`is_seva_only\`, \`has_variants\`, \`variants\`, \`sort_order\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('5', '1', 'ચાંદીનો વસ્ત્ર સેટ', 'चांदी का वस्त्र सेट', 'Silver Thread Vastra Set', 'silver-thread-vastra-set', 'ચાંદીના તારથી વણેલ પ્રિમિયમ વસ્ત્ર સેટ. ભગવાનના વિશેષ શ્રૃંગાર માટે — દિવાળી, જન્મોત્સવ જેવા મહાપર્વો માટે.', 'चांदी के तार से बुना प्रीमियम वस्त्र सेट. भगवान के विशेष श्रृंगार के लिए — दीवाली, जन्मोत्सव जैसे महापर्वों के लिए.', 'Premium vastra set woven with silver thread. For special adornment of the deity — ideal for Diwali, Janmotsav and other grand festivals.', '4000.00', '10', NULL, '1', '0', '0', '0', NULL, '5', '2026-04-09 09:40:21', '2026-04-09 09:40:21', NULL);
INSERT INTO \`temple_products\` (\`id\`, \`category_id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`slug\`, \`description_gu\`, \`description_hi\`, \`description_en\`, \`price\`, \`stock_quantity\`, \`image_path\`, \`is_active\`, \`is_featured\`, \`is_seva_only\`, \`has_variants\`, \`variants\`, \`sort_order\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('6', '1', 'ધોતી-ઉપરણો સેટ', 'धोती-उपरना सेट', 'Dhoti Uparna Set', 'dhoti-uparna-set', 'શુદ્ધ સફેદ ધોતી અને ઉપરણો — મંદિરના દૈનિક શ્રૃંગાર માટે. નરમ કોટન કાપડ, કેસરી બોર્ડર સાથે.', 'शुद्ध सफ़ेद धोती और उपरना — मंदिर के दैनिक श्रृंगार के लिए. नरम कॉटन कपड़ा, केसरी बॉर्डर के साथ.', 'Pure white dhoti and uparna for daily temple adornment. Soft cotton fabric with saffron border.', '1500.00', '20', NULL, '1', '0', '0', '0', NULL, '6', '2026-04-09 09:40:21', '2026-04-09 09:40:21', NULL);
INSERT INTO \`temple_products\` (\`id\`, \`category_id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`slug\`, \`description_gu\`, \`description_hi\`, \`description_en\`, \`price\`, \`stock_quantity\`, \`image_path\`, \`is_active\`, \`is_featured\`, \`is_seva_only\`, \`has_variants\`, \`variants\`, \`sort_order\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('7', '1', 'પટકો અને દુપટ્ટો', 'पटका और दुपट्टा', 'Patko and Dupatta', 'patko-and-dupatta', 'ભગવાનના કમર પર બાંધવાનો પટકો અને ખભા પર રાખવાનો દુપટ્ટો. સુંદર રંગ સંયોજન અને ઝરી કામ.', 'भगवान की कमर पर बांधने का पटका और कंधे पर रखने का दुपट्टा. सुंदर रंग संयोजन और ज़री काम.', 'Patko for the deity\'s waist and dupatta for the shoulders. Beautiful colour combination with zari work.', '1200.00', '26', NULL, '1', '0', '0', '0', NULL, '7', '2026-04-09 09:40:21', '2026-04-09 09:40:21', NULL);
INSERT INTO \`temple_products\` (\`id\`, \`category_id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`slug\`, \`description_gu\`, \`description_hi\`, \`description_en\`, \`price\`, \`stock_quantity\`, \`image_path\`, \`is_active\`, \`is_featured\`, \`is_seva_only\`, \`has_variants\`, \`variants\`, \`sort_order\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('8', '1', 'ફૂલોનો વસ્ત્ર હાર', 'फूलों का वस्त्र हार', 'Floral Vastra Garland', 'floral-vastra-garland', 'ફૂલોના આકારમાં કાપડથી બનાવેલ સુંદર હાર. લાંબા સમય સુધી ટકે છે, રોજિંદા શ્રૃંગાર માટે ઉત્તમ.', 'फूलों के आकार में कपड़े से बनी सुंदर माला. लंबे समय तक टिकती है, दैनिक श्रृंगार के लिए उत्तम.', 'Beautiful garland made from fabric in floral patterns. Long-lasting, perfect for daily adornment.', '1800.00', '38', NULL, '1', '0', '0', '0', NULL, '8', '2026-04-09 09:40:21', '2026-04-09 09:40:21', NULL);
INSERT INTO \`temple_products\` (\`id\`, \`category_id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`slug\`, \`description_gu\`, \`description_hi\`, \`description_en\`, \`price\`, \`stock_quantity\`, \`image_path\`, \`is_active\`, \`is_featured\`, \`is_seva_only\`, \`has_variants\`, \`variants\`, \`sort_order\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('9', '1', 'શિયાળુ ઊનનો વસ્ત્ર', 'शीतकालीन ऊनी वस्त्र', 'Winter Woolen Vastra', 'winter-woolen-vastra', 'શિયાળાની ઋતુ માટે ઊનનો ગરમ વસ્ત્ર. નરમ ઊન, કેસરી રંગ, ભરતકામ સાથે. ભગવાનને ઠંડીમાં ગરમાવો આપવા.', 'सर्दियों के मौसम के लिए ऊनी गर्म वस्त्र. नरम ऊन, केसरी रंग, कढ़ाई के साथ. भगवान को ठंड में गर्माहट देने के लिए.', 'Warm woolen vastra for the winter season. Soft wool, saffron colour, with embroidery. To keep the deity warm during cold months.', '2500.00', '19', NULL, '1', '0', '0', '0', NULL, '9', '2026-04-09 09:40:21', '2026-04-09 09:40:21', NULL);
INSERT INTO \`temple_products\` (\`id\`, \`category_id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`slug\`, \`description_gu\`, \`description_hi\`, \`description_en\`, \`price\`, \`stock_quantity\`, \`image_path\`, \`is_active\`, \`is_featured\`, \`is_seva_only\`, \`has_variants\`, \`variants\`, \`sort_order\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('10', '1', 'દિવાળી વિશેષ વસ્ત્ર', 'दीवाली विशेष वस्त्र', 'Diwali Special Vastra', 'diwali-special-vastra', 'દિવાળીના પાવન પર્વ માટે વિશેષ વસ્ત્ર. ભારે ઝરી કામ, મોતી અને કુંદનથી સજાવેલ. સીમિત માત્રામાં ઉપલબ્ધ.', 'दीवाली के पावन पर्व के लिए विशेष वस्त्र. भारी ज़री काम, मोती और कुंदन से सजाया हुआ. सीमित मात्रा में उपलब्ध.', 'Special vastra for the auspicious festival of Diwali. Heavy zari work, decorated with pearls and kundan. Available in limited quantity.', '3000.00', '29', NULL, '1', '1', '0', '0', NULL, '10', '2026-04-09 09:40:21', '2026-04-09 09:49:48', NULL);
INSERT INTO \`temple_products\` (\`id\`, \`category_id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`slug\`, \`description_gu\`, \`description_hi\`, \`description_en\`, \`price\`, \`stock_quantity\`, \`image_path\`, \`is_active\`, \`is_featured\`, \`is_seva_only\`, \`has_variants\`, \`variants\`, \`sort_order\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('19', '3', 'હનુમાન ચાલીસા — સચિત્ર', 'हनुमान चालीसा — सचित्र', 'Hanuman Chalisa Illustrated', 'hanuman-chalisa-illustrated', 'સુંદર ચિત્રો સાથેનું હનુમાન ચાલીસા પુસ્તક. ગુજરાતી અર્થ અને ટીકા સહિત. શ્રી પાતળિયા હનુમાનજી મંદિર દ્વારા પ્રકાશિત.', 'सुंदर चित्रों के साथ हनुमान चालीसा पुस्तक. गुजराती अर्थ और टीका सहित. श्री पातलिया हनुमानजी मंदिर द्वारा प्रकाशित.', 'Hanuman Chalisa book with beautiful illustrations. Including Gujarati meaning and commentary. Published by Shree Pataliya Hanumanji Temple.', '151.00', '22', NULL, '1', '0', '0', '0', NULL, '1', '2026-04-09 09:40:21', '2026-04-09 09:40:21', NULL);
INSERT INTO \`temple_products\` (\`id\`, \`category_id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`slug\`, \`description_gu\`, \`description_hi\`, \`description_en\`, \`price\`, \`stock_quantity\`, \`image_path\`, \`is_active\`, \`is_featured\`, \`is_seva_only\`, \`has_variants\`, \`variants\`, \`sort_order\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('20', '3', 'સુંદરકાંડ — ગુજરાતી ટીકા', 'सुंदरकांड — गुजराती टीका', 'Sundarkand with Gujarati Commentary', 'sundarkand-with-gujarati-commentary', 'તુલસીદાસજી રચિત રામચરિતમાનસનો સુંદરકાંડ — વિસ્તૃત ગુજરાતી ટીકા સાથે. ભક્તોના દૈનિક પાઠ માટે ઉત્તમ.', 'तुलसीदासजी रचित रामचरितमानस का सुंदरकांड — विस्तृत गुजराती टीका के साथ. भक्तों के दैनिक पाठ के लिए उत्तम.', 'Sundarkand from Tulsidas\'s Ramcharitmanas — with detailed Gujarati commentary. Ideal for daily recitation by devotees.', '351.00', '39', NULL, '1', '0', '0', '0', NULL, '2', '2026-04-09 09:40:21', '2026-04-09 09:40:21', NULL);
INSERT INTO \`temple_products\` (\`id\`, \`category_id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`slug\`, \`description_gu\`, \`description_hi\`, \`description_en\`, \`price\`, \`stock_quantity\`, \`image_path\`, \`is_active\`, \`is_featured\`, \`is_seva_only\`, \`has_variants\`, \`variants\`, \`sort_order\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('21', '3', 'શ્રી રામચરિતમાનસ', 'श्री रामचरितमानस', 'Shri Ramcharitmanas', 'shri-ramcharitmanas', 'ગોસ્વામી તુલસીદાસજી રચિત સંપૂર્ણ રામચરિતમાનસ. ગુજરાતી અનુવાદ અને ટીકા સહિત. મોટા અક્ષરોમાં છાપેલ.', 'गोस्वामी तुलसीदासजी रचित संपूर्ण रामचरितमानस. गुजराती अनुवाद और टीका सहित. बड़े अक्षरों में छपा हुआ.', 'Complete Ramcharitmanas by Goswami Tulsidas. With Gujarati translation and commentary. Printed in large font.', '551.00', '14', NULL, '1', '1', '0', '0', NULL, '3', '2026-04-09 09:40:21', '2026-04-09 09:40:21', NULL);
INSERT INTO \`temple_products\` (\`id\`, \`category_id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`slug\`, \`description_gu\`, \`description_hi\`, \`description_en\`, \`price\`, \`stock_quantity\`, \`image_path\`, \`is_active\`, \`is_featured\`, \`is_seva_only\`, \`has_variants\`, \`variants\`, \`sort_order\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('22', '3', 'બજરંગ બાણ અને આરતી સંગ્રહ', 'बजरंग बाण और आरती संग्रह', 'Bajrang Baan and Aarti Collection', 'bajrang-baan-and-aarti-collection', 'બજરંગ બાણ, હનુમાન ચાલીસા, આરતી અને સ્તુતિનો સંગ્રહ — એક જ પુસ્તકમાં. પોકેટ સાઈઝ, મુસાફરીમાં લઈ જવા યોગ્ય.', 'बजरंग बाण, हनुमान चालीसा, आरती और स्तुति का संग्रह — एक ही पुस्तक में. पॉकेट साइज़, यात्रा में ले जाने योग्य.', 'Collection of Bajrang Baan, Hanuman Chalisa, aarti and stuti — all in one book. Pocket size, convenient for travel.', '199.00', '19', NULL, '1', '0', '0', '0', NULL, '4', '2026-04-09 09:40:21', '2026-04-09 09:40:21', NULL);
INSERT INTO \`temple_products\` (\`id\`, \`category_id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`slug\`, \`description_gu\`, \`description_hi\`, \`description_en\`, \`price\`, \`stock_quantity\`, \`image_path\`, \`is_active\`, \`is_featured\`, \`is_seva_only\`, \`has_variants\`, \`variants\`, \`sort_order\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('23', '3', 'હનુમાન કથા — બાળકો માટે', 'हनुमान कथा — बच्चों के लिए', 'Hanuman Stories for Children', 'hanuman-stories-for-children', 'બાળકો માટે સરળ ભાષામાં હનુમાનજીની કથાઓ. રંગબેરંગી ચિત્રો સાથે. બાળકોને સંસ્કાર અને ભક્તિ શીખવતું પુસ્તક.', 'बच्चों के लिए सरल भाषा में हनुमानजी की कथाएं. रंग-बिरंगे चित्रों के साथ. बच्चों को संस्कार और भक्ति सिखाती पुस्तक.', 'Stories of Hanumanji in simple language for children. With colourful illustrations. A book that teaches children values and devotion.', '249.00', '43', NULL, '1', '0', '0', '0', NULL, '5', '2026-04-09 09:40:21', '2026-04-09 09:40:21', NULL);
INSERT INTO \`temple_products\` (\`id\`, \`category_id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`slug\`, \`description_gu\`, \`description_hi\`, \`description_en\`, \`price\`, \`stock_quantity\`, \`image_path\`, \`is_active\`, \`is_featured\`, \`is_seva_only\`, \`has_variants\`, \`variants\`, \`sort_order\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('24', '4', 'રુદ્રાક્ષ માળા', 'रुद्राक्ष माला', 'Rudraksha Mala', 'rudraksha-mala', 'અસલ 5-મુખી રુદ્રાક્ષ માળા — 108 દાણા. મંદિરમાં અભિમંત્રિત. જાપ અને ધ્યાન માટે ઉત્તમ.', 'असली 5-मुखी रुद्राक्ष माला — 108 दाने. मंदिर में अभिमंत्रित. जाप और ध्यान के लिए उत्तम.', 'Authentic 5-mukhi Rudraksha mala — 108 beads. Energised at the temple. Ideal for chanting and meditation.', '599.00', '44', NULL, '1', '0', '0', '0', NULL, '1', '2026-04-09 09:40:21', '2026-04-09 09:40:21', NULL);
INSERT INTO \`temple_products\` (\`id\`, \`category_id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`slug\`, \`description_gu\`, \`description_hi\`, \`description_en\`, \`price\`, \`stock_quantity\`, \`image_path\`, \`is_active\`, \`is_featured\`, \`is_seva_only\`, \`has_variants\`, \`variants\`, \`sort_order\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('25', '4', 'ચંદન માળા', 'चंदन माला', 'Sandalwood Mala', 'sandalwood-mala', 'શુદ્ધ ચંદનની સુગંધિત માળા — 108 દાણા. મંદિરમાં અભિમંત્રિત. ચંદનની કુદરતી સુગંધ, શાંતિ અને ધ્યાન માટે.', 'शुद्ध चंदन की सुगंधित माला — 108 दाने. मंदिर में अभिमंत्रित. चंदन की प्राकृतिक सुगंध, शांति और ध्यान के लिए.', 'Pure sandalwood fragrant mala — 108 beads. Energised at the temple. Natural sandalwood fragrance, for peace and meditation.', '899.00', '27', NULL, '1', '0', '0', '0', NULL, '2', '2026-04-09 09:40:21', '2026-04-09 09:40:21', NULL);
INSERT INTO \`temple_products\` (\`id\`, \`category_id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`slug\`, \`description_gu\`, \`description_hi\`, \`description_en\`, \`price\`, \`stock_quantity\`, \`image_path\`, \`is_active\`, \`is_featured\`, \`is_seva_only\`, \`has_variants\`, \`variants\`, \`sort_order\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('26', '4', 'તુલસી માળા', 'तुलसी माला', 'Tulsi Mala', 'tulsi-mala', 'પવિત્ર તુલસીની માળા — 108 દાણા. મંદિરમાં અભિમંત્રિત. રામ નામ જાપ અને દૈનિક પૂજા માટે.', 'पवित्र तुलसी की माला — 108 दाने. मंदिर में अभिमंत्रित. राम नाम जाप और दैनिक पूजा के लिए.', 'Sacred Tulsi mala — 108 beads. Energised at the temple. For Ram naam chanting and daily worship.', '299.00', '43', NULL, '1', '0', '0', '0', NULL, '3', '2026-04-09 09:40:21', '2026-04-09 09:40:21', NULL);
INSERT INTO \`temple_products\` (\`id\`, \`category_id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`slug\`, \`description_gu\`, \`description_hi\`, \`description_en\`, \`price\`, \`stock_quantity\`, \`image_path\`, \`is_active\`, \`is_featured\`, \`is_seva_only\`, \`has_variants\`, \`variants\`, \`sort_order\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('27', '4', 'શ્રી હનુમાનજી ફોટો ફ્રેમ — નાનો', 'श्री हनुमानजी फोटो फ्रेम — छोटा', 'Hanumanji Photo Frame Small', 'hanumanji-photo-frame-small', 'શ્રી પાતળિયા હનુમાનજીની મૂર્તિનો સુંદર ફોટો ફ્રેમ — 6×8 ઈંચ. ઘર અને ઓફિસમાં મૂકવા માટે, ગોલ્ડ કલરની ફ્રેમ.', 'श्री पातलिया हनुमानजी की मूर्ति का सुंदर फोटो फ्रेम — 6×8 इंच. घर और ऑफिस में रखने के लिए, गोल्ड कलर की फ्रेम.', 'Beautiful photo frame of Shree Pataliya Hanumanji\'s murti — 6x8 inches. For home and office display, gold coloured frame.', '399.00', '34', NULL, '1', '0', '0', '0', NULL, '4', '2026-04-09 09:40:21', '2026-04-09 09:40:21', NULL);
INSERT INTO \`temple_products\` (\`id\`, \`category_id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`slug\`, \`description_gu\`, \`description_hi\`, \`description_en\`, \`price\`, \`stock_quantity\`, \`image_path\`, \`is_active\`, \`is_featured\`, \`is_seva_only\`, \`has_variants\`, \`variants\`, \`sort_order\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('28', '4', 'શ્રી હનુમાનજી ફોટો ફ્રેમ — મોટો', 'श्री हनुमानजी फोटो फ्रेम — बड़ा', 'Hanumanji Photo Frame Large', 'hanumanji-photo-frame-large', 'શ્રી પાતળિયા હનુમાનજીની મૂર્તિનો મોટો ફોટો ફ્રેમ — 12×16 ઈંચ. પૂજા ઘર માટે ઉત્તમ, પ્રિમિયમ વૂડન ફ્રેમ.', 'श्री पातलिया हनुमानजी की मूर्ति का बड़ा फोटो फ्रेम — 12×16 इंच. पूजा घर के लिए उत्तम, प्रीमियम वुडन फ्रेम.', 'Large photo frame of Shree Pataliya Hanumanji\'s murti — 12x16 inches. Ideal for prayer room, premium wooden frame.', '799.00', '10', NULL, '1', '0', '0', '0', NULL, '5', '2026-04-09 09:40:21', '2026-04-09 09:40:21', NULL);
INSERT INTO \`temple_products\` (\`id\`, \`category_id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`slug\`, \`description_gu\`, \`description_hi\`, \`description_en\`, \`price\`, \`stock_quantity\`, \`image_path\`, \`is_active\`, \`is_featured\`, \`is_seva_only\`, \`has_variants\`, \`variants\`, \`sort_order\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('29', '4', 'ગદા કીચેન — પિત્તળ', 'गदा कीचेन — पीतल', 'Brass Gada Keychain', 'brass-gada-keychain', 'હનુમાનજીની ગદાના આકારની પિત્તળની કીચેન. મંદિરની યાદગીરી, ભેટ આપવા માટે ઉત્તમ.', 'हनुमानजी की गदा के आकार की पीतल की कीचेन. मंदिर की याद, उपहार देने के लिए उत्तम.', 'Brass keychain in the shape of Hanumanji\'s gada. A temple souvenir, perfect as a gift.', '149.00', '19', NULL, '1', '0', '0', '0', NULL, '6', '2026-04-09 09:40:21', '2026-04-09 09:40:21', NULL);
INSERT INTO \`temple_products\` (\`id\`, \`category_id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`slug\`, \`description_gu\`, \`description_hi\`, \`description_en\`, \`price\`, \`stock_quantity\`, \`image_path\`, \`is_active\`, \`is_featured\`, \`is_seva_only\`, \`has_variants\`, \`variants\`, \`sort_order\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('30', '4', 'ઓર્ગેનિક જ્યૂટ શોપિંગ બેગ', 'ऑर्गेनिक जूट शॉपिंग बैग', 'Organic Jute Shopping Bag', 'organic-jute-shopping-bag', 'મંદિરના લોગો અને હનુમાનજીની છબી સાથેની જ્યૂટ શોપિંગ બેગ. પર્યાવરણ-મૈત્રીપૂર્ણ, રોજિંદા ઉપયોગ માટે મજબૂત.', 'मंदिर के लोगो और हनुमानजी की छवि के साथ जूट शॉपिंग बैग. पर्यावरण-अनुकूल, दैनिक उपयोग के लिए मजबूत.', 'Jute shopping bag with temple logo and Hanumanji\'s image. Eco-friendly, sturdy for daily use.', '249.00', '10', NULL, '1', '0', '0', '0', NULL, '7', '2026-04-09 09:40:21', '2026-04-09 09:40:21', NULL);
INSERT INTO \`temple_products\` (\`id\`, \`category_id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`slug\`, \`description_gu\`, \`description_hi\`, \`description_en\`, \`price\`, \`stock_quantity\`, \`image_path\`, \`is_active\`, \`is_featured\`, \`is_seva_only\`, \`has_variants\`, \`variants\`, \`sort_order\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('31', '2', 'હનુમાનજી પેંડા પ્રસાદ', 'हनुमानजी पेड़ा प्रसाद', 'Hanumanji Peda Prasad', 'hanumanji-peda-prasad', 'શ્રી પાતળિયા હનુમાનજી મંદિરના પવિત્ર પેંડા પ્રસાદ. શુદ્ધ ઘીમાં બનાવેલ, મંદિરમાં અર્પણ કરાયેલ.', 'श्री पातलिया हनुमानजी मंदिर का पवित्र पेड़ा प्रसाद. शुद्ध घी में बना, मंदिर में अर्पित.', 'Sacred Peda Prasad from Shree Pataliya Hanumanji Temple. Made with pure ghee, offered at the temple.', '199.00', '48', NULL, '1', '1', '0', '1', '[{\"label\": \"250 ગ્રામ\", \"price\": 199}, {\"label\": \"500 ગ્રામ\", \"price\": 349}, {\"label\": \"1 કિલો\", \"price\": 649}]', '1', '2026-04-09 15:44:37', '2026-04-09 14:01:36', NULL);
INSERT INTO \`temple_products\` (\`id\`, \`category_id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`slug\`, \`description_gu\`, \`description_hi\`, \`description_en\`, \`price\`, \`stock_quantity\`, \`image_path\`, \`is_active\`, \`is_featured\`, \`is_seva_only\`, \`has_variants\`, \`variants\`, \`sort_order\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('32', '2', 'શ્રી લાડુ પ્રસાદ', 'श्री लड्डू प्रसाद', 'Shri Ladoo Prasad', 'shri-ladoo-prasad', 'શ્રી હનુમાનજીને પ્રિય લાડુ પ્રસાદ. દેશી ઘી અને ગોળમાં બનાવેલ પારંપરિક રેસિપી.', 'श्री हनुमानजी को प्रिय लड्डू प्रसाद. देसी घी और गुड़ में बनी पारंपरिक रेसिपी.', 'Ladoo Prasad dear to Shri Hanumanji. Traditional recipe made with desi ghee and jaggery.', '249.00', '39', NULL, '1', '0', '0', '1', '[{\"label\": \"250 ગ્રામ\", \"price\": 249}, {\"label\": \"500 ગ્રામ\", \"price\": 449}, {\"label\": \"1 કિલો\", \"price\": 799}]', '2', '2026-04-09 15:44:37', '2026-04-09 14:01:36', NULL);
INSERT INTO \`temple_products\` (\`id\`, \`category_id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`slug\`, \`description_gu\`, \`description_hi\`, \`description_en\`, \`price\`, \`stock_quantity\`, \`image_path\`, \`is_active\`, \`is_featured\`, \`is_seva_only\`, \`has_variants\`, \`variants\`, \`sort_order\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('33', '2', 'મિક્સ મીઠાઈ બોક્સ', 'मिक्स मिठाई बॉक्स', 'Mixed Sweet Box', 'mixed-sweet-box', 'વિવિધ મીઠાઈઓનું મિક્સ બોક્સ — પેંડા, લાડુ, બરફી. શુભ પ્રસંગો અને તહેવારો માટે ઉત્તમ.', 'विविध मिठाइयों का मिक्स बॉक्स — पेड़ा, लड्डू, बर्फी. शुभ अवसरों और त्योहारों के लिए उत्तम.', 'Mixed sweet box — Peda, Ladoo, Barfi. Perfect for auspicious occasions and festivals.', '899.00', '30', NULL, '1', '0', '0', '1', '[{\"label\": \"1 કિલો\", \"price\": 899}, {\"label\": \"2 કિલો\", \"price\": 1699}]', '3', '2026-04-09 15:44:37', '2026-04-09 15:44:37', NULL);
INSERT INTO \`temple_products\` (\`id\`, \`category_id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`slug\`, \`description_gu\`, \`description_hi\`, \`description_en\`, \`price\`, \`stock_quantity\`, \`image_path\`, \`is_active\`, \`is_featured\`, \`is_seva_only\`, \`has_variants\`, \`variants\`, \`sort_order\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('34', '2', 'હનુમાનજી પેંડા - 250 ગ્રામ', 'हनुमानजी पेड़ा - 250 ग्राम', 'Peda Box 250gm', 'peda-box-250gm', 'શ્રી પાતળિયા હનુમાનજી મંદિરના પવિત્ર પેંડા પ્રસાદ. શુદ્ધ ઘી અને ખાંડથી બનાવેલ, 250 ગ્રામ પેકિંગ.', 'श्री पातलिया हनुमानजी मंदिर का पवित्र पेड़ा प्रसाद. शुद्ध घी और चीनी से बना, 250 ग्राम पैकिंग.', 'Sacred peda prasad from Shree Pataliya Hanumanji Temple. Made with pure ghee and sugar, 250gm packing.', '199.00', '22', NULL, '1', '0', '0', '0', NULL, '1', '2026-04-10 14:18:31', '2026-04-10 14:18:31', NULL);
INSERT INTO \`temple_products\` (\`id\`, \`category_id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`slug\`, \`description_gu\`, \`description_hi\`, \`description_en\`, \`price\`, \`stock_quantity\`, \`image_path\`, \`is_active\`, \`is_featured\`, \`is_seva_only\`, \`has_variants\`, \`variants\`, \`sort_order\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('35', '2', 'હનુમાનજી પેંડા - 500 ગ્રામ', 'हनुमानजी पेड़ा - 500 ग्राम', 'Peda Box 500gm', 'peda-box-500gm', 'શ્રી પાતળિયા હનુમાનજી મંદિરના પવિત્ર પેંડા પ્રસાદ. શુદ્ધ ઘી અને ખાંડથી બનાવેલ, 500 ગ્રામ ફેમિલી પેક.', 'श्री पातलिया हनुमानजी मंदिर का पवित्र पेड़ा प्रसाद. शुद्ध घी और चीनी से बना, 500 ग्राम फैमिली पैक.', 'Sacred peda prasad from Shree Pataliya Hanumanji Temple. Made with pure ghee and sugar, 500gm family pack.', '349.00', '47', NULL, '1', '0', '0', '0', NULL, '2', '2026-04-10 14:18:31', '2026-04-10 14:18:31', NULL);
INSERT INTO \`temple_products\` (\`id\`, \`category_id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`slug\`, \`description_gu\`, \`description_hi\`, \`description_en\`, \`price\`, \`stock_quantity\`, \`image_path\`, \`is_active\`, \`is_featured\`, \`is_seva_only\`, \`has_variants\`, \`variants\`, \`sort_order\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('36', '2', 'હનુમાનજી પેંડા - 1 કિલો', 'हनुमानजी पेड़ा - 1 किलो', 'Peda Box 1kg', 'peda-box-1kg', 'શ્રી પાતળિયા હનુમાનજી મંદિરના પવિત્ર પેંડા પ્રસાદ. શુદ્ધ ઘી અને ખાંડથી બનાવેલ, 1 કિલો મોટું પેકિંગ — કુટુંબ અને સગાંવહાલાં માટે.', 'श्री पातलिया हनुमानजी मंदिर का पवित्र पेड़ा प्रसाद. शुद्ध घी और चीनी से बना, 1 किलो बड़ी पैकिंग — परिवार और रिश्तेदारों के लिए.', 'Sacred peda prasad from Shree Pataliya Hanumanji Temple. Made with pure ghee and sugar, 1kg large packing — for family and relatives.', '649.00', '39', NULL, '1', '0', '0', '0', NULL, '3', '2026-04-10 14:18:31', '2026-04-10 14:18:31', NULL);
INSERT INTO \`temple_products\` (\`id\`, \`category_id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`slug\`, \`description_gu\`, \`description_hi\`, \`description_en\`, \`price\`, \`stock_quantity\`, \`image_path\`, \`is_active\`, \`is_featured\`, \`is_seva_only\`, \`has_variants\`, \`variants\`, \`sort_order\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('37', '2', 'શ્રી લાડુ પ્રસાદ - 250 ગ્રામ', 'श्री लड्डू प्रसाद - 250 ग्राम', 'Ladoo Prasad 250gm', 'ladoo-prasad-250gm', 'હનુમાનજીને પ્રિય બેસન લાડુ પ્રસાદ. શુદ્ધ ઘી, બેસન અને ગોળથી બનાવેલ, 250 ગ્રામ પેકિંગ.', 'हनुमानजी को प्रिय बेसन लड्डू प्रसाद. शुद्ध घी, बेसन और गुड़ से बना, 250 ग्राम पैकिंग.', 'Besan ladoo prasad, beloved by Hanumanji. Made with pure ghee, besan and jaggery, 250gm packing.', '249.00', '25', NULL, '1', '0', '0', '0', NULL, '4', '2026-04-10 14:18:31', '2026-04-10 14:18:31', NULL);
INSERT INTO \`temple_products\` (\`id\`, \`category_id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`slug\`, \`description_gu\`, \`description_hi\`, \`description_en\`, \`price\`, \`stock_quantity\`, \`image_path\`, \`is_active\`, \`is_featured\`, \`is_seva_only\`, \`has_variants\`, \`variants\`, \`sort_order\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('38', '2', 'શ્રી લાડુ પ્રસાદ - 500 ગ્રામ', 'श्री लड्डू प्रसाद - 500 ग्राम', 'Ladoo Prasad 500gm', 'ladoo-prasad-500gm', 'હનુમાનજીને પ્રિય બેસન લાડુ પ્રસાદ. શુદ્ધ ઘી, બેસન અને ગોળથી બનાવેલ, 500 ગ્રામ ફેમિલી પેક.', 'हनुमानजी को प्रिय बेसन लड्डू प्रसाद. शुद्ध घी, बेसन और गुड़ से बना, 500 ग्राम फैमिली पैक.', 'Besan ladoo prasad, beloved by Hanumanji. Made with pure ghee, besan and jaggery, 500gm family pack.', '449.00', '18', NULL, '1', '1', '0', '0', NULL, '5', '2026-04-10 14:18:31', '2026-04-10 14:18:31', NULL);
INSERT INTO \`temple_products\` (\`id\`, \`category_id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`slug\`, \`description_gu\`, \`description_hi\`, \`description_en\`, \`price\`, \`stock_quantity\`, \`image_path\`, \`is_active\`, \`is_featured\`, \`is_seva_only\`, \`has_variants\`, \`variants\`, \`sort_order\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('39', '2', 'શ્રી લાડુ પ્રસાદ - 1 કિલો', 'श्री लड्डू प्रसाद - 1 किलो', 'Ladoo Prasad 1kg', 'ladoo-prasad-1kg', 'હનુમાનજીને પ્રિય બેસન લાડુ પ્રસાદ. શુદ્ધ ઘી, બેસન અને ગોળથી બનાવેલ, 1 કિલો મોટું પેકિંગ.', 'हनुमानजी को प्रिय बेसन लड्डू प्रसाद. शुद्ध घी, बेसन और गुड़ से बना, 1 किलो बड़ी पैकिंग.', 'Besan ladoo prasad, beloved by Hanumanji. Made with pure ghee, besan and jaggery, 1kg large packing.', '799.00', '49', NULL, '1', '0', '0', '0', NULL, '6', '2026-04-10 14:18:31', '2026-04-10 14:18:31', NULL);
INSERT INTO \`temple_products\` (\`id\`, \`category_id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`slug\`, \`description_gu\`, \`description_hi\`, \`description_en\`, \`price\`, \`stock_quantity\`, \`image_path\`, \`is_active\`, \`is_featured\`, \`is_seva_only\`, \`has_variants\`, \`variants\`, \`sort_order\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('40', '2', 'મિક્સ મીઠાઈ બોક્સ - 1 કિલો', 'मिक्स मिठाई बॉक्स - 1 किलो', 'Mixed Sweet Box 1kg', 'mixed-sweet-box-1kg', 'પેંડા, લાડુ, બરફી અને મોહનથાળ — ચાર પ્રકારની મીઠાઈનું મિક્સ બોક્સ. મંદિરના પવિત્ર પ્રસાદ, 1 કિલો ગિફ્ટ પેકિંગ.', 'पेड़ा, लड्डू, बर्फी और मोहनथाल — चार प्रकार की मिठाई का मिक्स बॉक्स. मंदिर का पवित्र प्रसाद, 1 किलो गिफ्ट पैकिंग.', 'Peda, ladoo, barfi and mohanthal — a mixed box of four types of sweets. Sacred temple prasad, 1kg gift packing.', '899.00', '15', NULL, '1', '0', '0', '0', NULL, '7', '2026-04-10 14:18:31', '2026-04-10 14:18:31', NULL);
INSERT INTO \`temple_products\` (\`id\`, \`category_id\`, \`name_gu\`, \`name_hi\`, \`name_en\`, \`slug\`, \`description_gu\`, \`description_hi\`, \`description_en\`, \`price\`, \`stock_quantity\`, \`image_path\`, \`is_active\`, \`is_featured\`, \`is_seva_only\`, \`has_variants\`, \`variants\`, \`sort_order\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('41', '2', 'મિક્સ મીઠાઈ બોક્સ - 2 કિલો', 'मिक्स मिठाई बॉक्स - 2 किलो', 'Mixed Sweet Box 2kg', 'mixed-sweet-box-2kg', 'પેંડા, લાડુ, બરફી અને મોહનથાળ — ચાર પ્રકારની મીઠાઈનું મોટું મિક્સ બોક્સ. તહેવારો અને પ્રસંગો માટે, 2 કિલો પ્રિમિયમ ગિફ્ટ પેકિંગ.', 'पेड़ा, लड्डू, बर्फी और मोहनथाल — चार प्रकार की मिठाई का बड़ा मिक्स बॉक्स. त्योहारों और अवसरों के लिए, 2 किलो प्रीमियम गिफ्ट पैकिंग.', 'Peda, ladoo, barfi and mohanthal — a large mixed box of four types of sweets. For festivals and occasions, 2kg premium gift packing.', '1699.00', '19', NULL, '1', '0', '0', '0', NULL, '8', '2026-04-10 14:18:31', '2026-04-10 14:18:31', NULL);

-- temple_blog_posts (3 rows)
TRUNCATE TABLE \`temple_blog_posts\`;
INSERT INTO \`temple_blog_posts\` (\`id\`, \`slug\`, \`title_gu\`, \`title_hi\`, \`title_en\`, \`body_gu\`, \`body_hi\`, \`body_en\`, \`excerpt_gu\`, \`featured_image_path\`, \`meta_title\`, \`meta_description\`, \`category\`, \`status\`, \`published_at\`, \`created_by\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('1', 'hanuman-chalisa-mahatmya', 'હનુમાન ચાલીસાનું મહાત્મ્ય', 'हनुमान चालीसा का महात्म्य', 'Significance of Hanuman Chalisa', '<p>હનુમાન ચાલીસા ગોસ્વામી તુલસીદાસજી રચિત એક મહાન સ્તોત્ર છે. ચાલીસ ચોપાઈઓ ધરાવતું આ સ્તોત્ર હનુમાનજીના ગુણો, લીલાઓ અને પરાક્રમોનું વર્ણન કરે છે.</p><p>દૈનિક હનુમાન ચાલીસાના પાઠથી ભય, રોગ અને દુઃખોનો નાશ થાય છે. શનિવારે અને મંગળવારે હનુમાન ચાલીસાનો પાઠ વિશેષ ફળદાયી માનવામાં આવે છે.</p>', '<p>हनुमान चालीसा गोस्वामी तुलसीदासजी रचित एक महान स्तोत्र है।</p>', NULL, 'હનુમાન ચાલીસા ગોસ્વામી તુલસીદાસજી રચિત એક મહાન સ્તોત્ર છે. દૈનિક પાઠનું મહત્વ જાણો.', NULL, NULL, NULL, 'spiritual', 'published', '2026-03-26 14:31:36', NULL, '2026-03-31 14:31:36', '2026-03-31 14:31:36', NULL);
INSERT INTO \`temple_blog_posts\` (\`id\`, \`slug\`, \`title_gu\`, \`title_hi\`, \`title_en\`, \`body_gu\`, \`body_hi\`, \`body_en\`, \`excerpt_gu\`, \`featured_image_path\`, \`meta_title\`, \`meta_description\`, \`category\`, \`status\`, \`published_at\`, \`created_by\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('2', 'mandir-itihas', 'શ્રી પાતળિયા હનુમાનજી મંદિરનો ઇતિહાસ', 'श्री पातळिया हनुमानजी मंदिर का इतिहास', 'History of Shree Pataliya Hanumanji Temple', '<p>અંતરજાલ, ગાંધીધામ, કચ્છમાં આવેલું શ્રી પાતળિયા હનુમાનજી મંદિર ભક્તોની આસ્થાનું કેન્દ્ર છે. મંદિરની સ્થાપના ઘણા દાયકાઓ પહેલા થઈ હતી.</p><p>ટ્રસ્ટ દ્વારા મંદિરના સતત વિકાસ અને ભક્તોની સેવા-સુશ્રુષા કરવામાં આવી રહી છે.</p>', NULL, NULL, 'શ્રી પાતળિયા હનુમાનજી મંદિરના ઇતિહાસ અને પરંપરા વિશે જાણો.', NULL, NULL, NULL, 'general', 'published', '2026-03-19 14:31:36', NULL, '2026-03-31 14:31:36', '2026-03-31 14:31:36', NULL);
INSERT INTO \`temple_blog_posts\` (\`id\`, \`slug\`, \`title_gu\`, \`title_hi\`, \`title_en\`, \`body_gu\`, \`body_hi\`, \`body_en\`, \`excerpt_gu\`, \`featured_image_path\`, \`meta_title\`, \`meta_description\`, \`category\`, \`status\`, \`published_at\`, \`created_by\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('3', 'shravan-mas-mahatva', 'શ્રાવણ માસનું મહત્વ', 'श्रावण मास का महत्व', 'Significance of Shravan Month', '<p>શ્રાવણ માસ હિંદુ ધર્મમાં અત્યંત પવિત્ર માનવામાં આવે છે. આ માસમાં શિવજી અને હનુમાનજીની પૂજા વિશેષ ફળદાયી છે.</p>', NULL, NULL, 'શ્રાવણ માસની પવિત્રતા અને વ્રત-ત્યોહારો વિશે.', NULL, NULL, NULL, 'spiritual', 'published', '2026-03-11 14:31:36', NULL, '2026-03-31 14:31:36', '2026-03-31 14:31:36', NULL);

-- temple_pages (3 rows)
TRUNCATE TABLE \`temple_pages\`;
INSERT INTO \`temple_pages\` (\`id\`, \`slug\`, \`title_gu\`, \`title_hi\`, \`title_en\`, \`body_gu\`, \`body_hi\`, \`body_en\`, \`featured_image_path\`, \`meta_title\`, \`meta_description\`, \`parent_slug\`, \`sort_order\`, \`status\`, \`template\`, \`created_by\`, \`published_at\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('1', 'parichay', 'પરિચય', 'परिचय', 'Introduction', '<p>શ્રી પાતળિયા હનુમાનજી સેવા ટ્રસ્ટ, અંતરજાલ, ગાંધીધામ, કચ્છ ખાતે આવેલું આ પવિત્ર મંદિર ભક્તોના શ્રદ્ધાનું કેન્દ્ર છે. મંદિરમાં હનુમાનજી મહારાજની ભવ્ય મૂર્તિ સ્થાપિત છે. દરરોજ સેંકડો ભક્તો દર્શન માટે આવે છે.</p>', '<p>श्री पातळिया हनुमानजी सेवा ट्रस्ट, अंतरजाल, गांधीधाम, कच्छ में स्थित यह पवित्र मंदिर भक्तों की श्रद्धा का केंद्र है। मंदिर में हनुमानजी महाराज की भव्य मूर्ति स्थापित है।</p>', '<p>Shree Pataliya Hanumanji Seva Trust temple, located in Antarjal, Gandhidham, Kutch, is a sacred center of devotion. The temple houses a grand idol of Hanumanji Maharaj and attracts hundreds of devotees daily.</p>', NULL, NULL, NULL, NULL, '1', 'published', 'default', NULL, '2026-03-31 14:31:36', '2026-03-31 14:31:36', '2026-03-31 14:31:36', NULL);
INSERT INTO \`temple_pages\` (\`id\`, \`slug\`, \`title_gu\`, \`title_hi\`, \`title_en\`, \`body_gu\`, \`body_hi\`, \`body_en\`, \`featured_image_path\`, \`meta_title\`, \`meta_description\`, \`parent_slug\`, \`sort_order\`, \`status\`, \`template\`, \`created_by\`, \`published_at\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('2', 'itihas', 'ઇતિહાસ', 'इतिहास', 'History', '<p>શ્રી પાતળિયા હનુમાનજી મંદિરનો ઇતિહાસ ઘણો પ્રાચીન છે. આ મંદિર ભક્તોની આસ્થા અને શ્રદ્ધાનું પ્રતીક છે. વર્ષોથી ટ્રસ્ટી મંડળ મંદિરના વિકાસ અને જીર્ણોદ્ધાર માટે સતત કાર્યરત છે.</p>', '<p>श्री पातळिया हनुमानजी मंदिर का इतिहास बहुत प्राचीन है। यह मंदिर भक्तों की आस्था और श्रद्धा का प्रतीक है।</p>', '<p>The history of Shree Pataliya Hanumanji Temple is ancient. The temple stands as a symbol of devotion and faith. The trust committee has been continuously working towards the development and renovation of the temple.</p>', NULL, NULL, NULL, NULL, '2', 'published', 'default', NULL, '2026-03-31 14:31:36', '2026-03-31 14:31:36', '2026-03-31 14:31:36', NULL);
INSERT INTO \`temple_pages\` (\`id\`, \`slug\`, \`title_gu\`, \`title_hi\`, \`title_en\`, \`body_gu\`, \`body_hi\`, \`body_en\`, \`featured_image_path\`, \`meta_title\`, \`meta_description\`, \`parent_slug\`, \`sort_order\`, \`status\`, \`template\`, \`created_by\`, \`published_at\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('3', 'mahima', 'મહિમા', 'महिमा', 'Glory', '<p>શ્રી પાતળિયા હનુમાનજી મંદિરની મહિમા અપરંપાર છે. અનેક ભક્તોએ અહીં દર્શન કરીને ચમત્કારિક અનુભવો કર્યા છે. હનુમાનજી મહારાજ ભક્તોની મનોકામના પૂર્ણ કરે છે.</p>', '<p>श्री पातळिया हनुमानजी मंदिर की महिमा अपरंपार है। अनेक भक्तों ने यहां दर्शन करके चमत्कारिक अनुभव किए हैं।</p>', '<p>The glory of Shree Pataliya Hanumanji Temple is immense. Many devotees have experienced miracles after visiting the temple. Hanumanji Maharaj fulfills the wishes of his devotees.</p>', NULL, NULL, NULL, NULL, '3', 'published', 'default', NULL, '2026-03-31 14:31:36', '2026-03-31 14:31:36', '2026-03-31 14:31:36', NULL);

-- temple_donation_campaigns (2 rows)
TRUNCATE TABLE \`temple_donation_campaigns\`;
INSERT INTO \`temple_donation_campaigns\` (\`id\`, \`title_gu\`, \`title_hi\`, \`title_en\`, \`slug\`, \`description_gu\`, \`description_hi\`, \`description_en\`, \`writeup_gu\`, \`writeup_hi\`, \`writeup_en\`, \`goal_amount\`, \`raised_amount\`, \`donor_count\`, \`image_path\`, \`media\`, \`faqs\`, \`start_date\`, \`end_date\`, \`is_active\`, \`show_donor_list\`, \`is_featured\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('1', 'મંદિર જીર્ણોદ્ધાર અભિયાન', 'मंदिर जीर्णोद्धार अभियान', 'Temple Renovation Campaign', 'temple-renovation-campaign', 'શ્રી પાતળિયા હનુમાનજી મંદિરના જીર્ણોદ્ધાર માટે ભક્તોના સહયોગની જરૂર છે. ગર્ભગૃહ, સભા મંડપ અને પરિસરના નવીનીકરણ માટે આ અભિયાન ચાલી રહ્યું છે.', 'श्री पातळिया हनुमानजी मंदिर के जीर्णोद्धार के लिए भक्तों के सहयोग की आवश्यकता है।', NULL, NULL, NULL, NULL, '2500000.00', '875000.00', '156', NULL, NULL, NULL, '2026-01-31', '2026-10-01', '1', '1', '0', '2026-03-31 14:31:36', '2026-03-31 14:31:36', NULL);
INSERT INTO \`temple_donation_campaigns\` (\`id\`, \`title_gu\`, \`title_hi\`, \`title_en\`, \`slug\`, \`description_gu\`, \`description_hi\`, \`description_en\`, \`writeup_gu\`, \`writeup_hi\`, \`writeup_en\`, \`goal_amount\`, \`raised_amount\`, \`donor_count\`, \`image_path\`, \`media\`, \`faqs\`, \`start_date\`, \`end_date\`, \`is_active\`, \`show_donor_list\`, \`is_featured\`, \`created_at\`, \`updated_at\`, \`deleted_at\`) VALUES ('2', 'ભોજનાલય વિસ્તરણ', 'भोजनालय विस्तारण', 'Bhojanalay Expansion', 'bhojanalay-expansion', 'દૈનિક ૫૦૦+ ભક્તોને ભોજન પ્રસાદ પીરસવા માટે ભોજનાલયનું વિસ્તરણ કરવામાં આવી રહ્યું છે.', NULL, NULL, NULL, NULL, NULL, '1000000.00', '320000.00', '78', NULL, NULL, NULL, '2026-03-03', '2026-07-31', '1', '1', '0', '2026-03-31 14:31:36', '2026-03-31 14:31:36', NULL);

-- temple_gallery_images (9 rows)
TRUNCATE TABLE \`temple_gallery_images\`;
INSERT INTO \`temple_gallery_images\` (\`id\`, \`title\`, \`description\`, \`image_path\`, \`thumbnail_path\`, \`medium_path\`, \`category\`, \`is_wallpaper\`, \`sort_order\`, \`uploaded_by\`, \`created_at\`, \`updated_at\`) VALUES ('1', 'મંદિર મુખ્ય દ્વાર', NULL, 'gallery/temple-main.jpg', NULL, NULL, 'temple', '0', '1', NULL, '2026-03-31 14:31:36', '2026-03-31 14:31:36');
INSERT INTO \`temple_gallery_images\` (\`id\`, \`title\`, \`description\`, \`image_path\`, \`thumbnail_path\`, \`medium_path\`, \`category\`, \`is_wallpaper\`, \`sort_order\`, \`uploaded_by\`, \`created_at\`, \`updated_at\`) VALUES ('2', 'હનુમાનજી મૂર્તિ', NULL, 'gallery/hanumanji-murti.jpg', NULL, NULL, 'deity', '0', '2', NULL, '2026-03-31 14:31:36', '2026-03-31 14:31:36');
INSERT INTO \`temple_gallery_images\` (\`id\`, \`title\`, \`description\`, \`image_path\`, \`thumbnail_path\`, \`medium_path\`, \`category\`, \`is_wallpaper\`, \`sort_order\`, \`uploaded_by\`, \`created_at\`, \`updated_at\`) VALUES ('3', 'શ્રૃંગાર દર્શન', NULL, 'gallery/shringar-darshan.jpg', NULL, NULL, 'deity', '0', '3', NULL, '2026-03-31 14:31:36', '2026-03-31 14:31:36');
INSERT INTO \`temple_gallery_images\` (\`id\`, \`title\`, \`description\`, \`image_path\`, \`thumbnail_path\`, \`medium_path\`, \`category\`, \`is_wallpaper\`, \`sort_order\`, \`uploaded_by\`, \`created_at\`, \`updated_at\`) VALUES ('4', 'હનુમાન જયંતિ ૨૦૨૫', NULL, 'gallery/jayanti-2025.jpg', NULL, NULL, 'festival', '0', '4', NULL, '2026-03-31 14:31:36', '2026-03-31 14:31:36');
INSERT INTO \`temple_gallery_images\` (\`id\`, \`title\`, \`description\`, \`image_path\`, \`thumbnail_path\`, \`medium_path\`, \`category\`, \`is_wallpaper\`, \`sort_order\`, \`uploaded_by\`, \`created_at\`, \`updated_at\`) VALUES ('5', 'દિવાળી ઉત્સવ', NULL, 'gallery/diwali-utsav.jpg', NULL, NULL, 'festival', '0', '5', NULL, '2026-03-31 14:31:36', '2026-03-31 14:31:36');
INSERT INTO \`temple_gallery_images\` (\`id\`, \`title\`, \`description\`, \`image_path\`, \`thumbnail_path\`, \`medium_path\`, \`category\`, \`is_wallpaper\`, \`sort_order\`, \`uploaded_by\`, \`created_at\`, \`updated_at\`) VALUES ('6', 'સુંદરકાંડ પાઠ', NULL, 'gallery/sundarkand-path.jpg', NULL, NULL, 'event', '0', '6', NULL, '2026-03-31 14:31:36', '2026-03-31 14:31:36');
INSERT INTO \`temple_gallery_images\` (\`id\`, \`title\`, \`description\`, \`image_path\`, \`thumbnail_path\`, \`medium_path\`, \`category\`, \`is_wallpaper\`, \`sort_order\`, \`uploaded_by\`, \`created_at\`, \`updated_at\`) VALUES ('7', 'ભોજનાલય', NULL, 'gallery/bhojanalay.jpg', NULL, NULL, 'temple', '0', '7', NULL, '2026-03-31 14:31:36', '2026-03-31 14:31:36');
INSERT INTO \`temple_gallery_images\` (\`id\`, \`title\`, \`description\`, \`image_path\`, \`thumbnail_path\`, \`medium_path\`, \`category\`, \`is_wallpaper\`, \`sort_order\`, \`uploaded_by\`, \`created_at\`, \`updated_at\`) VALUES ('8', 'મંદિર વૉલપેપર ૧', NULL, 'gallery/wallpaper-1.jpg', NULL, NULL, 'wallpaper', '1', '8', NULL, '2026-03-31 14:31:36', '2026-03-31 14:31:36');
INSERT INTO \`temple_gallery_images\` (\`id\`, \`title\`, \`description\`, \`image_path\`, \`thumbnail_path\`, \`medium_path\`, \`category\`, \`is_wallpaper\`, \`sort_order\`, \`uploaded_by\`, \`created_at\`, \`updated_at\`) VALUES ('9', 'મંદિર વૉલપેપર ૨', NULL, 'gallery/wallpaper-2.jpg', NULL, NULL, 'wallpaper', '1', '9', NULL, '2026-03-31 14:31:36', '2026-03-31 14:31:36');

SET FOREIGN_KEY_CHECKS=1;
