<?php

declare(strict_types=1);

namespace App\Observers;

use App\Models\HallBooking;
use App\Services\HallReminderScheduler;
use Illuminate\Support\Facades\Log;

/**
 * Keeps a hall booking's reminder schedule in step with its status.
 *
 * Mirrors SevaBookingObserver, including the single most important thing that
 * file teaches: this fires INSIDE PaymentCaptureService's transaction, so an
 * uncaught exception here rolls back the payment capture itself. That happened
 * in production on 2026-08-04. Reminders can be regenerated by the backfill
 * command; a lost capture cannot.
 */
class HallBookingObserver
{
    public function __construct(
        private readonly HallReminderScheduler $scheduler,
    ) {}

    public function created(HallBooking $booking): void
    {
        // Counter entry creates bookings already confirmed, so `updated` never
        // fires for them.
        if ($booking->status === 'confirmed') {
            $this->generateSafely($booking);
        }
    }

    public function updated(HallBooking $booking): void
    {
        if (! $booking->wasChanged('status')) {
            return;
        }

        if ($booking->status === 'confirmed') {
            $this->generateSafely($booking);

            return;
        }

        // Cancelled, refunded, completed — nothing left to remind about.
        try {
            $this->scheduler->cancelPendingFor($booking);
        } catch (\Throwable $e) {
            Log::error('HallBookingObserver: cancelling reminders failed', [
                'booking_id' => $booking->id,
                'error' => $e->getMessage(),
            ]);
        }
    }

    private function generateSafely(HallBooking $booking): void
    {
        try {
            $this->scheduler->generateForBooking($booking);
        } catch (\Throwable $e) {
            Log::error('HallBookingObserver: reminder generation failed — booking confirm continues', [
                'booking_id' => $booking->id,
                'error' => $e->getMessage(),
            ]);
        }
    }
}
